version: "3"

services:
  gympass-clone-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=gympass_clone_user
      - POSTGRESQL_PASSWORD=gympass_clone_123456
      - POSTGRESQL_DATABASE=gympass_clone_db
